[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["openai"]

[[redirects]]
  from = "/oauth/callback"
  to = "https://<your-site>/.netlify/functions/oauth-callback"
  status = 302
  force = true
